name: ✨ Feature Request
description: Suggest a new feature for Liftoff
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when I need to add GraphQL to my apps manually...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Liftoff could add a "Use GraphQL" checkbox when building apps, which would:
        - Install Apollo Client
        - Generate a graphql.ts file
        - Add example queries/mutations
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
      placeholder: I could use a separate VS Code extension, but integration would be better...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: Which part of Liftoff does this relate to?
      options:
        - App Builder (scaffolding & generation)
        - Agent System (AI behavior)
        - Template Library (app types)
        - Developer Experience (UX/UI)
        - Deployment (hosting integration)
        - Testing (test generation)
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Would use daily
        - Medium - Would use occasionally
        - Low - Nice to have
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: Example Use Cases
      description: Provide specific examples of how you'd use this feature
      placeholder: |
        1. Building a blog with comments → would generate GraphQL schema for posts/comments
        2. Building a SaaS dashboard → would set up subscriptions for real-time updates

  - type: textarea
    id: mockups
    attributes:
      label: Mockups / References
      description: Any mockups, screenshots, or links to similar implementations?
      placeholder: |
        Similar to how Bolt.new handles GraphQL: [link]
        Or attach screenshots/diagrams

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute to this feature (with guidance)
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature aligns with Liftoff's goal of rapid app prototyping
          required: true
